openapi: 3.0.0

info:
  title: "Swiftype App Search API"
  description: "Swiftype App Search API"
  version: "1.0"

components:
  parameters:
    pageCurrent:
      name: page.current
      in: query
      description: The current page
      schema:
        type: integer
        format: int32
        default: 1
      x-example: page.current=1
    pageSize:
      name: page.size
      in: query
      description: The number of results to show on each page
      schema:
        type: integer
        format: int32
        default: 20
      x-example: page.size=20
    engineNameParam:
      name: engine_name
      in: path
      description: Name of the engine
      required: true
      schema:
        type: string
      x-example": rent-a-car

paths:
  /engines:
    get:
      operationId: listEngines
      tags:
      - engine
      parameters:
      - $ref: "#/components/parameters/pageCurrent"
      - $ref: "#/components/parameters/pageSize"
      responses:
        '200':
          description: A simple string response

  /engines/{engine_name}:
    get:
      operationId: getEngine
      tags:
      - engine
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      responses:
        '200':
          description: A simple string response

  /engines/search/{engine_name}:
    post:
      operationId: search
      tags:
        - search
      parameters:
        - $ref: "#/components/parameters/engineNameParam"
        - $ref: "#/components/parameters/pageCurrent"
        - $ref: "#/components/parameters/pageSize"
      responses:
        '200':
          description: A simple string response
