openapi: 3.0.2

info:
  title: "Swiftype App Search API"
  description: "Swiftype App Search API"
  version: "1.0"

components:
  parameters:
    pageCurrent:
      name: page.current
      in: query
      description: The current page.
      schema:
        type: integer
        format: int32
    pageSize:
      name: page.size
      in: query
      description: The number of results to show on each page.
      schema:
        type: integer
        format: int32
    engineNameParam:
      name: engine_name
      in: path
      description: Name of the engine.
      required: true
      schema:
        type: string

paths:
  /engines:
    get:
      operationId: listEngines
      tags:
      - engine
      parameters:
      - $ref: "#/components/parameters/pageCurrent"
      - $ref: "#/components/parameters/pageSize"
      responses:
        "application/json":
          description: "List of available engines."
    post:
      operationId: createEngine
      tags:
      - engine
      parameters:
      - name: name
        in: query
        description: Engine name.
        required: true
        schema:
          type: string
      - name: language
        in: query
        description: Language code.
        schema:
          type: string
      responses:
        "application/json":
          description: "Engine data."

  /engines/{engine_name}:
    get:
      operationId: getEngine
      tags:
      - engine
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      responses:
        "application/json":
          description: "Engine data."
    delete:
      operationId: deleteEngine
      tags:
      - engine
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      responses:
        "application/json":
          description: "Engine deletion result."

  /engines/{engine_name}/search:
    post:
      operationId: search
      tags:
      - search
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      - name: query
        in: query
        description: Search query text.
        schema:
          type: string
        required: true
      - $ref: "#/components/parameters/pageCurrent"
      - $ref: "#/components/parameters/pageSize"
      - name: filters
        in: query
        description: Search query filters.
        schema:
          type: array
          items:
            type: object
        required: false
      - name: sort
        in: query
        description: Search query sort orders.
        schema:
          type: array
          items:
            type: object
        required: false
      - name: facets
        in: query
        description: Search query facets.
        schema:
          type: array
          items:
            type: object
        required: false
      - name: search_fields
        in: query
        description: Search query fields and weights.
        schema:
          type: array
          items:
            type: object
        required: false
      - name: boosts
        in: query
        description: Search query boosts.
        schema:
          type: array
          items:
            type: object
        required: false
      - name: group
        in: query
        description: Search result group specification.
        x-php-default-value: []
        schema:
          type: array
          items:
            type: object
        required: false
      - name: result_fields
        in: query
        description: Search result fields.
        x-php-default-value: []
        schema:
          type: array
          items:
            type: object
        required: false
      - name: analytics.tags
        in: query
        description: Analytics tags for the current search.
        x-php-default-value: []
        schema:
          type: array
          items:
            type: string
        required: false
      responses:
        "application/json":
          description: "Search result response."

  /engines/{engine_name}/multi_search:
    post:
      operationId: multiSearch
      tags:
      - search
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      - name: queries
        in: query
        description: Array of search queries.
        schema:
          type: array
          items:
            type: object
        required: false
      responses:
        "application/json":
          description: "Array of search result response."

  /engines/{engine_name}/schema:
    get:
      operationId: getSchema
      tags:
      - schema
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      responses:
        "application/json":
          description: "Engine schema"
    post:
      operationId: updateSchema
      tags:
      - schema
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      requestBody:
        description: Schema description.
        content:
          "*":
            schema:
              type: array
              items:
                type: object
      responses:
        "application/json":
          description: "Engine schema"

  /engines/{engine_name}/search_settings:
    get:
      operationId: getSearchSettings
      tags:
      - search_settings
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      responses:
        "application/json":
          description: "Search settings."
    put:
      operationId: updateSearchSettings
      tags:
      - search_settings
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      requestBody:
        description: Schema description.
        content:
          "*":
            schema:
              type: array
              items:
                type: object
      responses:
        "application/json":
          description: "Search settings."

  /engines/{engine_name}/search_settings/reset:
    post:
      operationId: resetSearchSettings
      tags:
      - search_settings
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      responses:
        "application/json":
          description: "Search settings."

  /engines/{engine_name}/documents:
    get:
      operationId: getDocuments
      tags:
      - documents
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      - name: ids
        in: query
        description: Documents ids.
        schema:
          type: array
          items:
            type: string
        required: true
      responses:
        "application/json":
          description: "Document indexing response."
    post:
      operationId: indexDocuments
      tags:
      - documents
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      requestBody:
        description: Indexed documents.
        content:
          "*":
            schema:
              type: array
              items:
                type: object
      responses:
        "application/json":
          description: "Document indexing response."
    patch:
      operationId: updateDocuments
      tags:
      - documents
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      requestBody:
        description: Documents update.
        content:
          "*":
            schema:
              type: array
              items:
                type: object
      responses:
        "application/json":
          description: "Document update response."
    delete:
      operationId: deleteDocuments
      tags:
      - documents
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      requestBody:
        description: Documents update.
        content:
          "*":
            schema:
              type: array
              items:
                type: string
      responses:
        "application/json":
          description: "Document delete response."

  /engines/{engine_name}/documents/list:
    get:
      operationId: listDocuments
      tags:
      - documents
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      - $ref: "#/components/parameters/pageCurrent"
      - $ref: "#/components/parameters/pageSize"
      responses:
        "application/json":
          description: "Document list."

  /engines/{engine_name}/synonyms:
    get:
      operationId: listSynonyms
      tags:
      - synonyms
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      - $ref: "#/components/parameters/pageCurrent"
      - $ref: "#/components/parameters/pageSize"
      responses:
        "application/json":
          description: "List of synonyms set"
    post:
      operationId: createSynonymSet
      tags:
      - synonyms
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      - name: synonyms
        in: query
        required: true
        schema:
          type: array
          items:
            type: string
      responses:
        "application/json":
          description: "Synonym set data."

  /engines/{engine_name}/synonyms/{synonym_set_id}:
    get:
      operationId: getSynonymSet
      tags:
      - synonyms
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      - name: synonym_set_id
        in: path
        description: Synonym set id.
        required: true
        schema:
          type: string
      responses:
        "application/json":
          description: "Synonym set data."
    delete:
      operationId: deleteSynonymSet
      tags:
      - synonyms
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      - name: synonym_set_id
        in: path
        description: Synonym set id.
        required: true
        schema:
          type: string
      responses:
        "application/json":
          description: "Delete operation result."

  /engines/{engine_name}/curations:
    get:
      operationId: listCurations
      tags:
      - curations
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      - $ref: "#/components/parameters/pageCurrent"
      - $ref: "#/components/parameters/pageSize"
      responses:
       "application/json":
         description: "List of curations."
    post:
     operationId: createCuration
     tags:
     - curations
     parameters:
     - $ref: "#/components/parameters/engineNameParam"
     - name: queries
       in: query
       required: true
       schema:
         type: array
         items:
           type: string
     - name: promoted
       in: query
       schema:
         type: array
         items:
           type: string
     - name: hidden
       in: query
       schema:
         type: array
         items:
           type: string
     responses:
       "application/json":
         description: "Curations data."

  /engines/{engine_name}/curations/{curation_id}:
    get:
      operationId: getCuration
      tags:
      - curations
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      - name: curation_id
        in: path
        description: Curation id.
        required: true
        schema:
          type: string
      responses:
        "application/json":
          description: "Curation data."
    delete:
      operationId: deleteCuration
      tags:
      - synonyms
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      - name: curation_id
        in: path
        description: Curation id.
        required: true
        schema:
          type: string
      responses:
        "application/json":
          description: "Delete operation result."
    put:
      operationId: updateCuration
      tags:
      - synonyms
      parameters:
      - $ref: "#/components/parameters/engineNameParam"
      - name: curation_id
        in: path
        description: Curation id.
        required: true
        schema:
          type: string
      - name: queries
        in: query
        required: true
        schema:
          type: array
          items:
            type: string
      - name: promoted
        in: query
        schema:
          type: array
          items:
            type: string
      - name: hidden
        in: query
        schema:
          type: array
          items:
            type: string
      responses:
        "application/json":
          description: "Delete operation result."
