language: php

php:
- '7.2'
- '5.6'
- '7.0'
- '7.1'
- '7.3'

env:
- TEST_SUITE=unit
- TEST_SUITE=integration

stages:
- qa
- test

cache:
  directories:
  - /home/travis/.composer/

install: composer install -n --prefer-dist
script: 
- export ST_ENGINE_NAME="php-test-$TRAVIS_JOB_NUMBER"
- vendor/bin/phpunit -c phpunit.xml.dist --testsuite $TEST_SUITE

jobs:
  include:
  - stage: qa
    script: vendor/bin/phplint . --exclude=vendor
  - stage: qa
    script: vendor/bin/phpcs --ignore=vendor,resources --standard=PSR12 .
