language: php

php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'
- '7.3'

env:
  - TEST_SUITE=unit
  - TEST_SUITE=integration

stages:
- qa
- test

jobs:
  include:
  - php: '7.2'
    script: ls
    stage: qa
  - script: env
