version: 2.1

executors:
  php:
    parameters:
      php-version:
        type: string
        default: "7.2"
    docker:
    - image: circleci/php:<< parameters.php-version >>-browsers


unit_tests: &unit_tests


integration_tests: &integration_tests
  environment:
    ST_ENGINE_NAME: php-integration-test-$CIRCLE_BUILD_NUM
  steps:
  - install_deps
  - run_integration_tests

commands:

  install_deps:
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.json" }}
    - run:
        name: Install composer dependencies
        command: composer install -n --prefer-dist
    - save_cache:
        paths:
        - ~/.composer/cache/
        key: v1-dependencies-{{ checksum "composer.json" }}

jobs:

  unit-tests:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
    - install_deps
    - run:
        name: Unit testing
        command: vendor/bin/phpunit -c phpunit.xml.dist --testsuite unit

  integration-tests:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
    - install_deps
    - run:
        name: Integration testing
        command: ST_ENGINE_NAME="php-integration-test-$CIRCLE_BUILD_NUM" vendor/bin/phpunit -c phpunit.xml.dist --testsuite integration

  phplint:
    executor: php
    steps:
    - install_deps
    - run:
        name:
        command: vendor/bin/phplint . --exclude=vendor

  phpcs:
    executor: php
    steps:
    - install_deps
    - run:
        name: PHPCS
        command: vendor/bin/phpcs --ignore=vendor,resources --standard=PSR12 .

workflows:
  version: 2
  qa:
    jobs:
    - phplint
    - phpcs
  php-73-tests:
    jobs:
    - unit-tests: { name: php-73-unit-tests, executor: { name: php, php-version: "7.3" } }
    - integration-tests: { name: php-73-integration-tests, executor: { name: php, php-version: "7.3" } }
  php-72-tests:
    jobs:
    - unit-tests: { name: php-72-unit-tests, executor: { name: php, php-version: "7.2" } }
    - integration-tests: { name: php-72-integration-tests, executor: { name: php, php-version: "7.2" } }
  php-71-tests:
    jobs:
    - unit-tests: { name: php-71-unit-tests, executor: { name: php, php-version: "7.1" } }
    - integration-tests: { name: php-71-integration-tests, executor: { name: php, php-version: "7.1" } }
  php-70-tests:
    jobs:
    - unit-tests: { name: php-70-unit-tests, executor: { name: php, php-version: "7.0" } }
    - integration-tests: { name: php-70-integration-tests, executor: { name: php, php-version: "7.0" } }
  php-56-tests:
    jobs:
    - unit-tests: { name: php-56-unit-tests, executor: { name: php, php-version: "5.6" } }
    - integration-tests: { name: php-56-integration-tests, executor: { name: php, php-version: "5.6" } }
